version: "3.9"

services:
  app:
    container_name: app
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      WAIT_HOSTS: postgres:5432
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB: db
      TRACKER_API_KEY: "175caabe-f4fb-4840-a226-a8cb867076af"
    ports:
      - "8000:8000"

  postgres:
    container_name: db
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db

#  pgadmin:
#    image: dpage/pgadmin4
#    depends_on:
#      - postgres
#    ports:
#      - "5555:80"
#    environment:
#      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
#      PGADMIN_DEFAULT_PASSWORD: admin
#    restart: unless-stopped