version: "3.9"

services:
  app:
    container_name: app
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      WAIT_HOSTS: postgres:5432
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB: db
    ports:
      - 8000:8000

  postgres:
    container_name: db
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db