version: '2'

services:
  app:
    container_name: app
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      WAIT_HOSTS: db:5432
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB: db
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/app
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports: 
      - "5432:5432"